/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as SignUpSsoCallbackRouteImport } from './routes/sign-up.sso-callback'
import { Route as SignUpContinueRouteImport } from './routes/sign-up.continue'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in.sso-callback'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AppServerIdRouteRouteImport } from './routes/app/$serverId/route'
import { Route as AppServerIdIndexRouteImport } from './routes/app/$serverId/index'
import { Route as AppServerIdChannelIdRouteImport } from './routes/app/$serverId/$channelId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SignUpSsoCallbackRoute = SignUpSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignUpRoute,
} as any)
const SignUpContinueRoute = SignUpContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignInRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServerIdRouteRoute = AppServerIdRouteRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServerIdIndexRoute = AppServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServerIdRouteRoute,
} as any)
const AppServerIdChannelIdRoute = AppServerIdChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => AppServerIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/app/$serverId': typeof AppServerIdRouteRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/continue': typeof SignUpContinueRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/$serverId/$channelId': typeof AppServerIdChannelIdRoute
  '/app/$serverId/': typeof AppServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/continue': typeof SignUpContinueRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/$serverId/$channelId': typeof AppServerIdChannelIdRoute
  '/app/$serverId': typeof AppServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/sign-in': typeof SignInRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/app/$serverId': typeof AppServerIdRouteRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/continue': typeof SignUpContinueRoute
  '/sign-up/sso-callback': typeof SignUpSsoCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/$serverId/$channelId': typeof AppServerIdChannelIdRoute
  '/app/$serverId/': typeof AppServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/app/$serverId'
    | '/invite/$code'
    | '/sign-in/sso-callback'
    | '/sign-up/continue'
    | '/sign-up/sso-callback'
    | '/app/'
    | '/app/$serverId/$channelId'
    | '/app/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/invite/$code'
    | '/sign-in/sso-callback'
    | '/sign-up/continue'
    | '/sign-up/sso-callback'
    | '/app'
    | '/app/$serverId/$channelId'
    | '/app/$serverId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/app/$serverId'
    | '/invite/$code'
    | '/sign-in/sso-callback'
    | '/sign-up/continue'
    | '/sign-up/sso-callback'
    | '/app/'
    | '/app/$serverId/$channelId'
    | '/app/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SignInRoute: typeof SignInRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/sign-up/sso-callback': {
      id: '/sign-up/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-up/sso-callback'
      preLoaderRoute: typeof SignUpSsoCallbackRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-up/continue': {
      id: '/sign-up/continue'
      path: '/continue'
      fullPath: '/sign-up/continue'
      preLoaderRoute: typeof SignUpContinueRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof SignInRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$serverId': {
      id: '/app/$serverId'
      path: '/$serverId'
      fullPath: '/app/$serverId'
      preLoaderRoute: typeof AppServerIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$serverId/': {
      id: '/app/$serverId/'
      path: '/'
      fullPath: '/app/$serverId/'
      preLoaderRoute: typeof AppServerIdIndexRouteImport
      parentRoute: typeof AppServerIdRouteRoute
    }
    '/app/$serverId/$channelId': {
      id: '/app/$serverId/$channelId'
      path: '/$channelId'
      fullPath: '/app/$serverId/$channelId'
      preLoaderRoute: typeof AppServerIdChannelIdRouteImport
      parentRoute: typeof AppServerIdRouteRoute
    }
  }
}

interface AppServerIdRouteRouteChildren {
  AppServerIdChannelIdRoute: typeof AppServerIdChannelIdRoute
  AppServerIdIndexRoute: typeof AppServerIdIndexRoute
}

const AppServerIdRouteRouteChildren: AppServerIdRouteRouteChildren = {
  AppServerIdChannelIdRoute: AppServerIdChannelIdRoute,
  AppServerIdIndexRoute: AppServerIdIndexRoute,
}

const AppServerIdRouteRouteWithChildren =
  AppServerIdRouteRoute._addFileChildren(AppServerIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppServerIdRouteRoute: typeof AppServerIdRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppServerIdRouteRoute: AppServerIdRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SignInRouteChildren {
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
}

const SignInRouteChildren: SignInRouteChildren = {
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
}

const SignInRouteWithChildren =
  SignInRoute._addFileChildren(SignInRouteChildren)

interface SignUpRouteChildren {
  SignUpContinueRoute: typeof SignUpContinueRoute
  SignUpSsoCallbackRoute: typeof SignUpSsoCallbackRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpContinueRoute: SignUpContinueRoute,
  SignUpSsoCallbackRoute: SignUpSsoCallbackRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SignInRoute: SignInRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
